https://ri.bb.com.br/informacoes-financeiras/central-de-resultados/

https://ri.unipar.com/mercado-de-capitais/dividendos-e-bonificacoes/

https://www.santander.com.br/ri/dividendos

https://ri.klabin.com.br/dividendos-e-jcp/

https://ri.taesa.com.br/informacoes-financeiras/dividendos/

https://ri.cemig.com.br/

In [6]:
import pandas as pd

df = pd.read_excel('bb.xlsx', sheet_name='Dividendos JCP')

df

,Índice,1T06,2T06,3T06,4T06,1T07,2T07,3T07,4T07,1T08,...,4T20,1T21,2T21,3T21,4T21,1T22,2T22,3T22,4T22,1T23
0,União Federal,675.999082,438.174407,249.281546,342.850329,386.989131,293.479487,374.695722,326.417831,613.265298,...,790.161465,802.534988,736.567197,828.739773,1411.24583,1266.064199,1463.014348,1545.060592,1654.130911,1618.160444
1,Previ,129.951295,70.745447,41.525958,57.112885,64.465639,48.888545,62.417748,52.284347,98.286609,...,74.31743,75.356345,69.068695,77.296899,131.686678,117.625486,135.345752,142.295505,152.340558,149.094535
2,BNDES,53.873939,17.686525,18.298384,25.166753,28.406739,21.542703,27.504337,12.654728,23.775372,...,0,0,0,0,0,0,0,0,0,0
3,PF,23.574808,27.689062,15.125817,20.80335,22.715553,17.118071,21.897823,26.04685,55.068806,...,188.782,245.269845,220.988155,267.122811,461.05553,369.151949,416.398034,419.801096,455.111668,423.501645
4,PJ,9.809988,22.036183,12.471946,17.153338,21.817914,16.424228,19.044272,21.1515,43.927757,...,164.456036,130.17994,112.34892,136.545543,243.050921,208.475838,270.798328,256.701408,262.956088,257.170426
5,Capital Estrangeiro,30.844829,42.071583,26.28881,36.156415,39.121011,29.898288,40.054764,48.210423,104.662515,...,355.825111,344.894557,327.914204,340.753714,563.517583,560.224395,628.252658,713.358746,769.910978,775.105021
6,Incorporação BNC,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,TOTAL,924.053941,618.403207,362.992461,499.243071,563.515989,427.351322,545.614666,486.765678,938.986356,...,1573.608,1598.338,1466.956,1650.528,2810.654,2521.674,2913.948,3077.363,3294.603,3223.173
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,Mar/06,Jun/06,Set/06,Dez/06,Mar/07,Jun/07,Set/07,Dez/07,Mar/08,...,Dez/20,Mar/21,Jun/21,Set/21,Dez/21,Mar/22,Jun/22,Set/22,Dez/22,Mar/23
10,Dividendos e JCP / Ação - Acionistas (R$),1.172273,0.7493,0.439822,0.604911,0.682788,0.172601,0.220366,0.196598,0.369362,...,0.551516,0.560152,0.514108,0.578443,0.985019,0.883686,1.021153,1.078419,1.154548,1.129441
11,Dividend yield (%) 12M ¹,2.112203,1.499189,0.925941,0.945174,1.023823,1.632395,0.713389,0.646703,1.59828,...,4.363726,6.29267,6.094351,7.774535,9.142886,8.533487,10.390048,10.301695,11.914213,11.207736